apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicas
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: myapp  # should refer pod definition label name
  template:
    metadata:        
      name: myapp-replicas
      labels:        
        app: myapp  #shoudld same as matchLabels app name
    spec:            
      containers:     
        - name: myapp-container
          image: nginx
          ports:
            - containerPort: 80