apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp-service
spec:
  type: NodePort      
  selector:
    app: myapp
  ports:
    - name: http
      port: 80         
      targetPort: 80    
      nodePort: 31235




#type, selectors and ports are the high level objets of spec

#Selectors are used to load balance the traffic across PODS using labels and port whatever we difined.
#ex: our POD label is:-   app:: myapp-nodeport-service, If we diefind the same labels in selector means
#This servie is going to identify this POD( app: myapp in pod file) based on the defined the labels in service. (app: myapp##) 
#means based on the selector(selector: myapp-nodeport-service) in service file, it find the POD name which is defind on PODS then its send the trafiic across the PODS

## IMP

#Service will expose the POD to the external world. Traffic ll distributed to the respective selector (selector: myapp) whose 
#selector: myapp matches with the PODS labels app:myapp in Pods file
