apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp-service
spec:
  type: NodePort      
  selector:
    app: myapp
  ports:
    - name: http
      port: 80         
      targetPort: 80    
      nodePort: 31235
